version: "3.9"
   
services:
  db:
    image: mysql:5.7
    volumes:
        - .:/docker-entrypoint-initdb.d/
    environment:
        - MYSQL_ROOT_PASSWORD=django
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=django
        - MYSQL_PASSWORD=django
    ports:
        - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS:  db:3306