FROM apache/airflow:2.0.1
USER root
RUN mkdir /app
COPY ./Requirements/airflow_requirements.txt /app/airflow_requirements.txt
WORKDIR /app
RUN apt-get update -yqq \
    && apt-get upgrade -yqq \
    && pip install --upgrade pip \
    && pip install bs4 \
    && pip install requests \
    && pip install pymysql
    #&& pip install -r airflow_requirements.txt