FROM python:3
ENV PYTHONUNBUFFERED=1
RUN mkdir -p /code
WORKDIR /code
COPY ./Requirements/django_requirements.txt .
RUN pip install -r django_requirements.txt
COPY ./django_code/ .
CMD ["python", "./manage.py", "makemigrations"]
CMD ["python", "./manage.py", "migrate"]
CMD ["python", "./manage.py", "runserver", "0.0.0.0:8000"]